name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Replace with your default branch (e.g., "master")

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./client    # Deploy the "client" folder’s contents
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: false        # Clean old files
          force_orphan: true       # Force orphan branch (gh-pages)